Support ime's chained to modifiers
liveview-native/liveview-client-swiftui pull request #1230
Opened 2024-01-17 08:47 UTC by NduatiK

Support `Color(...).opacity(0.25)` in

```swift
foregroundStyle(Color(.displayP3, red: 0.4627, green: 0.8392, blue: 1.0).opacity(0.25))
```

Resolves https://github.com/liveview-native/live_view_native_stylesheet/issues/41

2024-01-17 08:48 UTC, NduatiK commented
@carson-katri, please confirm the output AST in the test is correct

2024-01-17 19:40 UTC, carson-katri requested changes
AST looks good to me 👍

2024-01-17 19:40 UTC, carson-katri commented on lib/live_view_native/swiftui/rules_parser/post_processors.ex
> +    # |> IO.inspect()
Can this be removed?
```suggestion
```

2024-01-18 14:03 UTC, NduatiK commented on lib/live_view_native/swiftui/rules_parser/post_processors.ex
> +    # |> IO.inspect()
Removed, thanks

2024-01-18 16:09 UTC, carson-katri approved these changes

2024-01-18 16:09 UTC, merged