Add background modifier
liveview-native/liveview-client-swiftui pull request #734
Opened 2023-03-24 01:05 UTC by supernintendo

Adds support for the [background](https://developer.apple.com/documentation/swiftui/view/background(alignment:content:)) modifier and adds the ability to use namespaced child elements when decoding modifiers. This is based on @carson-katri's idea for handling nested views within modifiers via Content Entities as described [here](https://github.com/liveview-native/liveview-client-swiftui/issues/170).

```heex
<VStack>
  <Spacer />
  <HStack>
    <Image system-name="heart.fill" modifiers={@native |> background(alignment: :center, content: "heart_bg") |> foreground_style(primary: {:color, :red})}>
      <background:heart_bg>
        <Circle modifiers={@native |> frame(width: 32, height: 32)} />
      </background:heart_bg>
    </Image>
  </HStack>

  <Spacer />

  <HStack>
    <Text modifiers={@native |> background(alignment: :center, content: "text_bg") |> foreground_style(primary: {:linear_gradient, %{gradient: {:colors, [:orange, :indigo, :purple]}, start_point: {0, 0}, end_point: {1, 1}}})}>
      liveviewnative
      <background:text_bg>
        <RoundedRectangle corner-radius="8" modifiers={@native |> frame(width: 192, height: 64)} />
      </background:text_bg>
    </Text>
  </HStack>
  <Spacer />
</VStack>
```

![Screenshot 2023-03-23 at 5 58 14 PM](https://user-images.githubusercontent.com/5893007/227397402-67a09c5e-c5da-4201-a628-b46ff7d3b4f1.png)

There are a few outstanding issues with this PR:

1. The `foreground_style` modifier influences the background content instead of the `background_style` modifier which doesn't appear to do anything. I'm not sure why this is but from what I can tell the native [backgroundStyle modifier](https://developer.apple.com/documentation/swiftui/grid/backgroundstyle(_:)) only affects nested content rendered using the `in:` constructor and not content passed to `content`.

2. There seem to be performance limitations with nested modifier views in my implementation. By rendering too many elements with background modifiers within the same view I'm able to produce a crash, although I haven't investigated this enough to know what might be causing it.

3. The string format for `content` when referencing namespaced child views could be a bit confusing. I'd like to tweak the Elixir modifier schema so that it accepts an atom instead, which should ameliorate this.

2023-03-24 17:37 UTC, shadowfacts requested changes
Something is definitely weird with how the background/foreground modifiers are interacting, though it's not obvious to me what the issue is.

In plain old SwiftUI, the following (translated directly from your example) results in just a red circle appearing, since the foreground style is applying to both the Circle and the Image.
```swift
Image(systemName: "heart.fill")
	.background(alignment: .center) {
		Circle()
			.frame(width: 32, height: 32)
	}
	.foregroundStyle(.red)
```

To get the result that you actually show, you'd need to move the foreground style _inside_ the background modifier so that it only applies to the Circle:
```swift
Image(systemName: "heart.fill")
	.background(alignment: .center) {
		Circle()
			.frame(width: 32, height: 32)
			.foregroundStyle(.red)
	}
```

2023-03-24 17:37 UTC, shadowfacts commented on Sources/LiveViewNative/ViewTree.swift
> +
The context and element shouldn't be stored and passed through the decoder, they can be accessed from the modifier using their respective property wrappers:
```swift
struct MyModifier<R: RootRegistry>: ViewModifier, Decodable {
    @ObservedElement private var element
    @LiveContext<R> private var context
    // etc.
}
```

2023-03-24 17:37 UTC, shadowfacts commented on Sources/LiveViewNative/Registries/BuiltinRegistry.swift
> +struct BuiltinRegistry<R: RootRegistry>: BuiltinRegistryProtocol {
This makes sense, but can you also remove the `R` generic type and the `context` parameter from the `lookup` method, for consistency?

2023-03-24 17:47 UTC, carson-katri commented
`Image` does not respect the `foreground_style` modifier because it uses a `foregroundColor` modifier in its body, which uses the system foreground color when set to `nil`. The example below produces the same result as the provided screenshot:

```swift
Image(systemName: "heart.fill")
            .foregroundColor(nil)
            .background(alignment: .center) {
                Circle()
                    .frame(width: 32, height: 32)
            }
            .foregroundStyle(.red)
```

https://github.com/liveview-native/liveview-client-swiftui/blob/931a824c85f17fc2e85924fde82b1d3d23cee6ad/Sources/LiveViewNative/Views/Images/Image.swift#L45

The attribute should probably be removed from `Image`.

Text has [the same problem](https://github.com/liveview-native/liveview-client-swiftui/blob/931a824c85f17fc2e85924fde82b1d3d23cee6ad/Sources/LiveViewNative/Views/Text%20Input%20and%20Output/Text.swift#L78). The `textColor`, `font`, and `fontWeight` attributes should likely be replaced with modifiers as well.

2023-03-24 17:49 UTC, carson-katri commented
RE the `background_style` modifier, this would require using the [`BackgroundStyle`](https://developer.apple.com/documentation/swiftui/shapestyle/background) shape style. Background content created in this way uses the foreground style by default.

2023-03-24 17:57 UTC, shadowfacts commented
Ah, that is indeed the case. We do probably want general modifiers for them, but, I think the `foregroundColor`, `font`, and `fontWeight` modifiers need to remain attributes on the Text view as well, since doing them through our usual modifiers architecture would break composing Texts with different styles.

I think a workaround would be having a helpers like `foregroundColorIfPresent` for Text that only applies the underlying modifier if the value is non-nil, rather than applying `.foregroundColor(nil)` as currently happens.

2023-03-28 13:21 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/BackgroundModifier.swift
> +struct BackgroundModifier<R: RootRegistry>: ViewModifier, Decodable {
Could you document the modifier?

2023-04-01 18:21 UTC, supernintendo commented on Sources/LiveViewNative/Modifiers/BackgroundModifier.swift
> +struct BackgroundModifier<R: RootRegistry>: ViewModifier, Decodable {
@carson-katri Done!

2023-04-01 21:29 UTC, supernintendo commented
> 

I added `foregroundColorIfPresent` to fix that in [f7e7172](https://github.com/liveview-native/liveview-client-swiftui/pull/734/commits/f7e71724f2ecf6fa8f02e7610e241cf6e5449173). Let me know if there are other examples of this I should address, although maybe that's out of scope for this pull request?

2023-04-03 14:29 UTC, carson-katri approved these changes

2023-04-03 16:35 UTC, shadowfacts requested changes
This looks good, just needs a slight tweak to make the docs visible

2023-04-07 14:49 UTC, shadowfacts approved these changes

2023-04-14 03:01 UTC, merged