Add disabled modifier
liveview-native/liveview-client-swiftui pull request #755
Opened 2023-03-30 03:46 UTC by supernintendo

This PR adds support for the [disabled modifier](https://developer.apple.com/documentation/swiftui/view/disabled(_:)). Related issue: https://github.com/liveview-native/liveview-client-swiftui/issues/546

```heex
<VStack>
  <Button modifiers={disabled(@native, disabled: true)}>
    <Label>This button is disabled</Label>
  </Button>
  <Button modifiers={disabled(@native, disabled: false)}>
    <Label>This button is not</Label>
  </Button>
</VStack>
```

![Screenshot 2023-03-29 at 8 43 27 PM](https://user-images.githubusercontent.com/5893007/228723562-c6eee873-fbb6-4036-8232-219a55cbe3c7.png)

2023-03-30 18:13 UTC, shadowfacts requested changes

2023-03-31 18:52 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/DisabledModifier.swift
> +    private let disabled: Bool?
This needs the `@_documentation(visibility:)` attribute for the symbol link to work.
```suggestion
    #if swift(>=5.8)
    @_documentation(visibility: public)
    #endif
    private let disabled: Bool
```

2023-03-31 18:52 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/DisabledModifier.swift
> +    }
Looks like this init is unused.
```suggestion
```

2023-04-03 14:32 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/View Configuration Modifiers/DisabledModifier.swift
> +struct DisabledModifier: ViewModifier, Decodable, Equatable {
```suggestion
#if swift(>=5.8)
@_documentation(visibility: public)
#endif
struct DisabledModifier: ViewModifier, Decodable, Equatable {
```

2023-04-07 14:48 UTC, shadowfacts approved these changes

2023-04-13 02:30 UTC, merged