Add monospaced and monospacedDigit modifiers
liveview-native/liveview-client-swiftui pull request #768
Opened 2023-04-02 01:44 UTC by supernintendo

Adds the [monospaced](https://developer.apple.com/documentation/swiftui/view/monospaced(_:)) and [monospacedDigit](https://developer.apple.com/documentation/swiftui/view/monospaceddigit()) modifiers:

```heex
<VStack>
  <Label modifiers={monospaced(@native, is_active: true)}>This text is monospaced</Label>
  <Label modifiers={monospaced(@native, is_active: false)}>This text is not</Label>
  <Label modifiers={monospaced_digit(@native)}>1234567890</Label>
  <Label>1234567890</Label>
</VStack>
```

![Screenshot 2023-04-01 at 6 41 42 PM](https://user-images.githubusercontent.com/5893007/229326497-8acd66c4-2d24-4356-8747-c9d77d1c5dce.png)

Closes https://github.com/liveview-native/liveview-client-swiftui/issues/304
Closes https://github.com/liveview-native/liveview-client-swiftui/issues/305

2023-04-03 15:08 UTC, carson-katri requested changes

2023-04-03 15:08 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/Text Input and Output Modifiers/MonospacedDigitModifier.swift
> +        self
```suggestion
```

2023-04-07 14:46 UTC, shadowfacts approved these changes

2023-04-13 17:24 UTC, carson-katri approved these changes

2023-04-14 03:03 UTC, merged