Add `swipe_actions` modifier
liveview-native/liveview-client-swiftui pull request #897
Opened 2023-05-01 21:49 UTC by supernintendo

This PR adds support for the [swipeActions](https://developer.apple.com/documentation/swiftui/view/swipeactions(edge:allowsfullswipe:content:)) List modifier.

```heex
<VStack id="swipe_actions">
  <Text><%= @swipe_event_message %></Text>
  <Spacer />
  <List>
    <%= for {item, is_unread?} <- [{"Foo", true}, {"Bar", false}, {"Baz", false}] do %>
      <HStack
        id={item}
        modifiers={
          @native
          |> swipe_actions(edge: :leading, allows_full_swipe: false, content: :hello)
          |> swipe_actions(edge: :trailing, allows_full_swipe: false, content: :delete)
          |> swipe_actions(edge: :trailing, allows_full_swipe: false, content: :flag)
        }>
        <Text><%= item %></Text>
        <swipe_actions:hello>
          <%= if is_unread? do %>
            <Button>
              <Image system-name="envelope.badge" />
            </Button>
          <% else %>
            <Button modifiers={tint(@native, color: :accent)}>
              <Image system-name="envelope.open" />
            </Button>
          <% end %>
        </swipe_actions:hello>
        <swipe_actions:flag>
          <% tapping the flag_item event will update the @swipe_event_message assign %>
          <Button phx-click="flag_item" phx-value-item={item}>
            <Image system-name="flag" />
          </Button>
        </swipe_actions:flag>
        <swipe_actions:delete>
          <Button modifiers={tint(@native, color: :red)}>
            <Image system-name="trash" />
          </Button>
        </swipe_actions:delete>
      </HStack>
    <% end %>
  </List>
</VStack>
```

<img width="647" alt="Screenshot 2023-05-01 at 10 23 05 AM" src="https://user-images.githubusercontent.com/5893007/235537570-38117ff6-4c26-42fc-b482-0b704efe45f8.png">

Closes #549

2023-05-02 18:27 UTC, shadowfacts approved these changes

2023-05-03 15:22 UTC, dginsburg commented on Sources/LiveViewNative/Modifiers/Lists Modifiers/SwipeActionsModifier.swift
> +/// * ``allowsFullSwipe``
The Elixir code will still use snake case: `allows_full_swipe`

2023-05-03 17:18 UTC, supernintendo commented on Sources/LiveViewNative/Modifiers/Lists Modifiers/SwipeActionsModifier.swift
> +        case allowsFullSwipe = "allows_full_swipe"
Oh cool, thanks 🙂

2023-05-03 20:46 UTC, shadowfacts approved these changes

2023-05-03 20:48 UTC, carson-katri requested changes

2023-05-03 20:48 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/Lists Modifiers/SwipeActionsModifier.swift
> +            context.buildChildren(of: element, withTagName: self.content, namespace: "swipe_actions")
This will need to be updated since I merged #787

2023-05-18 14:03 UTC, carson-katri requested changes

2023-05-18 14:03 UTC, carson-katri commented on Sources/LiveViewNative/Modifiers/Lists Modifiers/SwipeActionsModifier.swift
> +    let content: String
The `@_documentation` attribute should be on the property, not the doc comment.
```suggestion
    /// The edge of the list item to associate the swipe actions with.
    #if swift(>=5.8)
    @_documentation(visibility: public)
    #endif
    let edge: HorizontalEdge
    /// A boolean value that indicates whether the swipe action should be allowed to span the entire width of the screen.
    #if swift(>=5.8)
    @_documentation(visibility: public)
    #endif
    let allowsFullSwipe: Bool
    /// The content of the swipe action.
    #if swift(>=5.8)
    @_documentation(visibility: public)
    #endif
    let content: String
```

2023-05-23 17:23 UTC, carson-katri approved these changes

2023-05-26 19:42 UTC, merged