Add `symbol_variant` modifier
liveview-native/liveview-client-swiftui pull request #961
Opened 2023-05-30 14:31 UTC by dginsburg

Closes #333

2023-05-30 15:14 UTC, carson-katri requested changes
There is some missing functionality here. In SwiftUI, the variants can be chained together, such as `.circle.fill`.

You may be able to implement it like `Edge.Set` (https://github.com/liveview-native/liveview-client-swiftui/blob/fa403b5d77ed41220da587f0a3993bc891d27ed8/Sources/LiveViewNative/Utils/Edge.swift#L32-L68), with a similar Elixir type as well: https://github.com/liveview-native/liveview-client-swiftui/blob/fa403b5d77ed41220da587f0a3993bc891d27ed8/lib/live_view_native_swift_ui/types/edge_set.ex.

Then `.circle.fill` could be created as `[:circle, :fill]` in Elixir.

2023-06-12 20:12 UTC, supernintendo approved these changes

2023-06-13 11:15 UTC, AZholtkevych commented
@carson-katri could you please unblock this one

2023-06-13 13:32 UTC, carson-katri approved these changes

2023-06-13 13:32 UTC, merged